### ISSUE TITLE
IJulia runtime not loaded in Jupyter

### ISSUE THREAD

**Issue by NOTtheMessiah** [shashi/Patchwork.jl#12]
Running the Hello World example doesn't work because it seems that `Patchwork.load_js_runtime()` isn't run because  `isdefined(Main, :IJulia)` returns false. Is there a better way to check the existence of a package?

Issue can be circumvented just by running `Patchwork.load_js_runtime()` in Jupyter.

**Comment by NOTtheMessiah** [comment]
My bad, I was using the Jupyter v0.3.11 kernel config that I forgot to delete.

**Comment by rohitvarkey** [comment]
Hmm. I keep getting this error intermittently. Worth raising an issue on `IJulia` I guess.
