### ISSUE TITLE
`jsonfmt` has no method matching `jsonfmt(::Patchwork.Overwrite{Patchwork.Elem{:svg,:text}})`

### ISSUE THREAD

**Issue by lucasb-eyer** [shashi/Patchwork.jl#2]
When I run `Interact.jl`'s [third example notebook](https://github.com/JuliaLang/Interact.jl/blob/master/doc/notebooks/03-Interactive%20Diagrams%20and%20Plots.ipynb), upon toggling the "both" checkbox of the `Gadfly.jl` plot, I see this in the Jupyter kernel's output:

```
KERNEL EXCEPTION
`jsonfmt` has no method matching jsonfmt(::Patchwork.Overwrite{Patchwork.Elem{:svg,:text}})

 in push! at /home/beyer/.julia/v0.4/Reactive/src/Reactive.jl:271
 in recv at /home/beyer/.julia/v0.4/Interact/src/Interact.jl:50
 in handle_msg at /home/beyer/.julia/v0.4/Interact/src/IJulia/handle_msg.jl:4
 in anonymous at /home/beyer/.julia/v0.4/Interact/src/IJulia/setup.jl:196
 in comm_msg at /home/beyer/.julia/v0.4/IJulia/src/comm_manager.jl:119
 in eventloop at /home/beyer/.julia/v0.4/IJulia/src/IJulia.jl:123
 in anonymous at task.jl:340
```

This is the only place in the four example notebooks where this happens, but I don't know if it breaks anything or not because of JuliaLang/Interact.jl#46.

**Comment by shashi** [comment]
Thanks! This had me pretty bad too. This is fixed on Patchwork master now. :)
