### ISSUE TITLE
Render to html string

### ISSUE THREAD

**Issue by stanonyime** [shashi/Patchwork.jl#5]
How do you render a node to raw html? I would want to h1("hello world") parsed to 

``` html
<h1>Hello World </h1>
```

and bound to a variable of my choosing

**Comment by shashi** [comment]
Well this will be tricky. Patchwork nodes represent the DOM which are in many ways different from the HTML markup, there is no way to convert to HTML without losing at least some information.

**Comment by EricForgy** [comment]
Hi shashi,

This looks like a cool package and I had the same question as stanonyime.

I'm not an HTML expert, but I've played around quite a bit with d3 for manipulating the DOM and I don't understand your response. I would think that you should be able to start with a DOM representation and generate an HTML document that would render that DOM. What am I missing? If there is information in Patchwork that would be lost in constructing an HTML document, what kind of info would that be and is that info necessary for rendering a page or would it be more about interactivity, signals, etc.?

If I understand, your build.js is based on node.js, but I am interested in using Patchwork directly with a Julia server and I thought writing a Patchwork DOM to HTML might be a good way to go.

Any thoughts? Thanks :)

Edit:

In case you might have some better ideas, maybe I'll try to describe what I'm thinking...

I'd like to use HttpServer.jl and when I receive an HTTP POST request, I'd like the controller to return an HTML document based on the body of the HTTP POST (including generated scripts) together with some Julia calculations. Is that a horrible idea? :)

**Comment by shashi** [comment]
> I would think that you should be able to start with a DOM representation and generate an HTML document that would render that DOM.

That is not true because you can only write "attributes" in HTML but not DOM properties http://stackoverflow.com/questions/258469/what-is-the-difference-between-attribute-and-property

For your purpose you should consider using [Hiccup](https://github.com/JunoLab/Hiccup.jl) and [Mux](https://github.com/JuliaWeb/Mux.jl)

**Comment by EricForgy** [comment]
Hi shashi,

Thanks for the quick reply and for correcting me on the HTML (I said I wasn't an expert :)).

Not giving up, to set properties when writing an HTML document from Patchwork, in principle, could you generate embedded d3 (or jQuery) scripts to set those properties?

Thanks also for the reference to Hiccup and Mux. I am familiar with Mux, but decided to work directly with HttpServer.jl, but not familiar with Hiccup so will check it out :+1:
